GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json

{
    "email": "rio@mail.com",
    "fullname": "Rio",
    "gender": "L"
}

###
PUT http://localhost:8080/users?userId=5
Content-Type: application/json

{
    "email": "riooo@mail.com",
    "fullname": "Riooo",
    "gender": "L"
}

###
DELETE http://localhost:8080/users/5